import "./globals.css";
import type { Metadata } from "next";
import { Nerko_One } from "next/font/google";

export const metadata: Metadata = {
  title: "Juice app",
  description: "Generated by Vandeco",
};
const nerko = Nerko_One({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={nerko.className}>{children}</body>
    </html>
  );
}
